//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : BbsBean.java
//  @ Date : 2019-06-21
//  @ Author : 
//
//




public class BbsBean implements Inter, Inter {
	private int num;
	protected String name;
	public String sub;
	public java.sql. Date nalja;
	public int pay;
	public int getNum() {
	
	}
	
	public void setNum(int a) {
	
	}
	
	public String update(int a, String b, String c, int d) {
	
	}
}
